const data={
rapido:{label:"01 / INDEPENDENT PRODUCT CONCEPT · 2026",title:"Rapido - No-Network Booking",desc:"A product-thinking case study about continuity when mobile connectivity fails.",html:"<h3>Problem framing</h3><p>The starting point was a real-world constraint: a user may need a ride at the exact moment their internet connection is weak or unavailable.</p><h3>Research direction</h3><p>I explored the behaviour and failure points around network loss, including booking initiation, OTP verification, confirmation, failed requests and connectivity recovery.</p><h3>Product opportunity</h3><p>Instead of treating no network as a dead end, the product could offer a fallback path using OTP/SMS while keeping the user informed about system status.</p><h3>What the interface communicates</h3><p>Simple actions, clear status and minimal interaction are prioritized because the user is already operating under a constrained condition.</p>"},
basket:{label:"02 / TUTEDUDE · FIRST ASSIGNMENT · 2026",title:"Clean Basket",desc:"A service-product case study for a laundry experience.",html:"<h3>Problem space</h3><p>The concept targets hostel/PG residents and working professionals who may not have enough time to wash clothes themselves.</p><h3>Journey thinking</h3><p>I worked through the service journey from choosing a service to provider details, booking, order tracking and payment states.</p><h3>Research-to-design link</h3><p>The project helped me practice turning a broad service problem into clearer user flows, information structure, wireframes, prototype interactions and UI decisions.</p>"},
world:{label:"03 / INDEPENDENT UX RESEARCH · IN PROGRESS",title:"World Watch",desc:"A research-led information product for complex global crises.",html:"<h3>Problem space</h3><p>Information about wars and natural disasters can be distributed across many updates, locations and sources. The concept explores how to make that information easier to discover and understand.</p><h3>Research questions</h3><p>How might users discover an ongoing crisis? What information helps them understand severity and affected regions? How can the product connect understanding with responsible support?</p><h3>Product structure</h3><p>The work explores information architecture around crisis updates, affected regions, casualties, critical needs, location-based discovery and relief opportunities.</p><h3>Status</h3><p>This is an independent project and is still in progress.</p>"},
paytm:{label:"04 / PAYTM DESIGN COMPETITION · 2026",title:"Speak. Confirm. Sent.",desc:"Reimagining Paytm UPI P2P with voice.",html:"<h3>Problem</h3><p>Sending money can involve finding the recipient, entering the amount and navigating several steps. A user conversation in the presentation described this friction in a time-sensitive situation.</p><h3>Research insight</h3><p>“People don’t think in UPI IDs. They think in people.” The concept lets users express the payment naturally while the product handles the typing and prepares the transaction.</p><h3>Product concept</h3><p>Two entry points were explored: an in-app microphone inside Pay Anyone and OS-level voice through Google Assistant.</p><h3>Trust and safety</h3><p>Voice does not directly send money. Recipient and amount are shown for review, with an edit option, followed by fingerprint authentication or PIN fallback.</p><h3>Outcome</h3><div class='flow'><span>Speak</span><span>Detect</span><span>Review</span><span>Authenticate</span><span>Sent</span></div><p>The presentation describes the goal as making P2P payments faster while retaining user control and secure confirmation.</p>"}
};
const modal=document.getElementById("modal");
document.querySelectorAll(".case-btn").forEach(b=>b.addEventListener("click",()=>{const d=data[b.dataset.id];document.getElementById("ml").textContent=d.label;document.getElementById("mt").textContent=d.title;document.getElementById("md").textContent=d.desc;document.getElementById("mc").innerHTML=d.html;modal.classList.add("open")}));
document.querySelector(".close").onclick=()=>modal.classList.remove("open");
modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")modal.classList.remove("open")});
const menu=document.querySelector(".menu"),nav=document.querySelector(".nav nav");menu.onclick=()=>{nav.style.display=nav.style.display==="flex"?"none":"flex";nav.style.position="absolute";nav.style.top="78px";nav.style.left="0";nav.style.right="0";nav.style.padding="20px 6vw";nav.style.background="#f6f5f0";nav.style.flexDirection="column";nav.style.borderBottom="1px solid #ddd"};
